name: api_client
description: API client package using retrofit and build_runner
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  test: ^1.21.0
